### ISSUE TITLE
Agile mentioned...just to clarify? 

### ISSUE THREAD

**Issue by tban65** [Azure/Microsoft-TDSP#1]
In the email TDSP was described as "an agile, iterative, data science methodology ". Does this mean it will follow the Agile development process?

**Comment by gopitk** [comment]
Thanks for the question. In TDSP, we recommend an Agile development process (like Scrum, Kanban) for your data science projects which results in productionized intelligent applications. Data science is inherently an iterative discovery of your problem/solution space, making and validating hypothesis etc with close collaboration between data scientists, data engineers, software engineers, domain expert roles. So it is natural to adopt Agile software development for data science also. However, you may still benefit from adopting some of the practices in TDSP even if your org uses another software development process. 

Let us know if I have addressed your question.

**Comment by stephenra** [comment]
Thanks for the response @gopitk. In TDSP, do you prescribe or favor any particular Agile development process over another -- that is, have you found any one Agile method a better fit for TDSP?

**Comment by tban65** [comment]
Stephen:

For the purposes of BizTalk development, I prefer a looser approach to Agile as the work itself is almost more Waterfall than Agile. That said, certain parts of Agile work well for project management. At a previous shop Agile was pretty rigid and a lot of it was a waste of time which could have been more efficiently utilized had they let the Developers make the rules and not forced to follow ceremonies so much.

So I would say unless there appears to be severe drop off in productivity, managing things as they have been managed would fall under the “if it’s not broken, don’t fix it” category?

Tom Banaski | BizTalk Developer
Office: 630.383.7314
Clover Technologies Group | www.clovertech.comhttp://www.clovertech.com/| Tom.Banaski@CLOVERTECH.commailto:Tom.Banaski@CLOVERTECH.com

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this message in error, please destroy it (and any attachments) and notify the sender immediately. The recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by gopitk** [comment]
Thanks for the inputs Tom. I agree that if your current software dev process is working for most part you can adopt additional practices in TDSP for your data science initiatives . If you are starting off new in processes, start with something well defined like Scrum (for more product development type stuff or where the iteration level work planning feels natural to you) OR Kanban (typically for a continuous flow of requests - for eg if you are an internal data science team handling individual analysis requests from your business units) and then tweak your practices from there once you learn from your new process and retrospectives.

**Comment by stephenra** [comment]
@gopitk @tban65 Thank you both for your feedback.

**Comment by tban65** [comment]
One thing I did like and find enormous value in Agile were the daily standip meetings—they lend reansparency to the team’s status and allow members to relate whether they feel a need for additional team collaboration on a given task or feature. Also breaking the work into tasks makes it easier to make sure steps are mot missed as the tasks het reviewed by the team when the Sprint is setup.
