### ISSUE TITLE
Project template

### ISSUE THREAD

**Issue by rodrigour** [Azure/Microsoft-TDSP#6]
Would be great to add a Project Online template with the main Data Science activities.

**Comment by deguhath** [comment]
We are working towards develop and release an Agile project and work management template with the data science activities like you're suggesting. Thanks for the feedback.

**Comment by rajashekarmandadi** [comment]
Hello Team, 

Myself Raj I work as a Project Manager for Data Science Projects at our Company, I would like to have a demo on how to use Team Data Science Process and apply it for our Data Science Projects to improve the efficiency and productivity of our projects. Let me know if you have someone from Microsoft who can help us with the demo. We are already using Microsoft Azure ML, ADF etc, as we need to establish a process using TDSP we need support to establish TDSP Process from you.

Best Regards,
Raj
